<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
    <title>Novo site</title>

    <!-- CSS  -->
    <link href="<?php echo $this->getBaseLocation() ?>public/css/style.css" type="text/css" rel="stylesheet" media="screen"/>

</head>
<body>
Novo site.
</body>
</html>
